version: '2.1'

jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            sudo pip install -r requirements.txt
            sudo pip install -r dev_requirements.txt
      - run:
          name: Run tests
          command: |
            python -m unittest discover -v
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build container
          command: |
            export IMAGE=${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
            docker build -t ${IMAGE}:${CIRCLE_SHA1} .
      - run:
          name: Test container
          command: |
              export IMAGE=${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
              docker run -it ${IMAGE}:${CIRCLE_SHA1} --help


workflows:
  version: '2.1'
  check:
    jobs:
      - test
      - build:
          requires:
            - test
